# Generated by Django 2.0.4 on 2018-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180419_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='studentID',
            new_name='student_id',
        ),
    ]
