# Generated by Django 2.0.4 on 2018-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180419_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
