# Generated by Django 2.0.4 on 2018-05-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180504_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_authenticated',
        ),
    ]
