# Generated by Django 2.0.4 on 2018-05-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_is_email_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_auths', to='accounts.Profile')),
            ],
        ),
    ]
