# Generated by Django 2.0.4 on 2018-05-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauth',
            name='is_email_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
