# Generated by Django 2.0.4 on 2018-05-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_emailauth_is_email_authenticated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliationAuth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_affiliation_authenticated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='emailauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
