# Generated by Django 2.0.4 on 2018-05-08 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180508_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailauth',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_auth', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
