# Generated by Django 2.0.4 on 2018-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20180420_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='expired_at',
            field=models.DateField(blank=True),
        ),
    ]
