# Generated by Django 2.0.4 on 2018-04-19 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_auto_20180420_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
