# Generated by Django 2.0.4 on 2018-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_auto_20180420_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='assentients',
            field=models.ManyToManyField(blank=True, related_name='assentient_petitions', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='petitions', to='petitions.Category'),
        ),
    ]
