# Generated by Django 2.0.4 on 2018-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0008_auto_20180427_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
